### ISSUE TITLE
Do not work with Gnome 3.32

### ISSUE THREAD

**Issue by Nik-mmzd** [maweki/twitchlive-extension#49]
```
Extension "TwitchLive_Panel@extensions.maweki.de" had error: TypeError: this._construct is not a function
```

**Comment by maweki** [comment]
Damn.

People fixed this: https://github.com/micheleg/dash-to-dock/pull/881

We will have to do the same fixes across the codebase and break compatibility for 3.30 and lower.
