### PR TITLE
feat: support gnome shell version 3.32

### LINKED ISSUE #49: Do not work with Gnome 3.32
```
Extension "TwitchLive_Panel@extensions.maweki.de" had error: TypeError: this._construct is not a function
```

### PR DESCRIPTION
**Pull request by oae**
I have updated the extension to work on Gnome 3.32. This fixes #49 but it breaks the compatibility with older versions of gnome.

### CODE REVIEW

**Comment by maweki** [comment]
Thank you. That's great. I will merge it this week. Do you know how "broken" the compatibility is? I mean, do we crash 3.20? Otherwise I will just update the description and hint here.

**Comment by oae** [comment]
I couldn't check deeply but on Ubuntu 18.04 with Gnome 3.28.3. I was getting `GObject.registerClass() used with invalid base class`.

**Comment by maweki** [comment]
Okay, good. If we're not killing the shell then we're fine. I'll do this then. ETA good friday.
