### PR TITLE
Add compatibility with gnome 3.34

### PR DESCRIPTION
**Pull request by Nibbler999**
Extension fails in gnome 3.34 with the following error

`TypeError: item.get_size_info is not a function`

when updating the list of streams.

`PopupBaseMenuItem` changed from an ES6 class to a GObject class in gnome-shell 3.34 which apparently breaks inheritance. This can be fixed by using `GObject.registerClass` to handle the inheritance but this breaks compatibility with 3.32. Seeing as only 2 small methods are being added these can be converted to normal functions so it works with both 3.32 and 3.34.

`get_streamer` appears to be unused so was dropped.

Tested with Fedora 30 and 31.

### CODE REVIEW

**Comment by maweki** [comment]
This looks good. Thank you. I will make a release in the next few hours.
